#!/usr/bin/env ruby
##############################################################################
# DIRECTORIES
##############################################################################


app/              # Core application (app) code, including models, views, controllers, and helpers.

app/assets        # Applications assets such as cascading style sheets (CSS), JavaScript files, and images.

bin/              # Binary executable files.

config/           # Application configuration.

db/               # Database files.

doc/              # Documentation for the application.

lib/              # Library modules.

lib/assets        # Library assets such as cascading style sheets (CSS), JavaScript files, and images.

log/              # Application log files.

public/           # Data accessible to the public (e.g. via web browsers), such as error pages.

bin/rails         # A program for generating code, opening console sessions, or starting a local server.

test/             # Application tests.

tmp/              # Temporary files.

vendor/           # Third-party code such as plugins and gems.

vendor/assets     # Third-party assets such as cascading style sheets (CSS), JavaScript files, and images.

config.ru         # A configuration file for Rack middleware.


##############################################################################
# VARIABLES
##############################################################################


##############################################################################
# FILE COMMANDS
##############################################################################
